version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: automation-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automation
      MYSQL_USER: automation
      MYSQL_PASSWORD: automationpass
    ports:
      - "3306:3306"
    volumes:
      - automation-db-data:/var/lib/mysql
    networks:
      - automation-network


  adminer:
    image: adminer
    container_name: automation-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - automation-network


volumes:
  automation-db-data:
  automation-app-data:

networks:
  automation-network:
    driver: bridge
