version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: automation-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: automation
      MYSQL_USER: smartuser
      MYSQL_PASSWORD: automationpass
    ports:
      - "3306:3306"
    volumes:
      - automation-db-data:/var/lib/mysql
    networks:
      - automation-network

  app:
    build: .
    container_name: automation-app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/automation?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: smartuser
      SPRING_DATASOURCE_PASSWORD: smartpass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
    volumes:
      - automation-app-data:/app/data
      - /home/user/Desktop/files:/app/file_storage
    restart: on-failure
    networks:
      - automation-network

  adminer:
    image: adminer
    container_name: automation-adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - db
    networks:
      - automation-network

volumes:
  automation-db-data:
  automation-app-data:

networks:
  automation-network:
    driver: bridge

